source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ALLocalizables_Example' do
  pod "ALLocalizables", :path => "../"
end

target 'ALLocalizables_Tests'  do
  pod "ALLocalizables", :path => "../"
end
