source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ALLocalizables_Example' do
  pod "ALLocalizables", :path => "../"
end

target 'ALLocalizables_Tests'  do
  pod "ALLocalizables", :path => "../"
end

# Build configurations
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
